### ISSUE TITLE
Do not show notice to users before auth

### ISSUE THREAD

**Issue by avi-perl** [dizballanze/django-admin-env-notice#20]
* django-admin-env-notice version: N/A
* Django version: N/A
* Python version: N/A
* Operating System: N/A

### Description

I'm wondering if you would be open to adding a new feature or accepting a PR along the following lines:

On my sites, I like to put additional information in the env bar, such as the name of the git branch the site is on, the sha, and other information that ideally, I'd want to keep out of the public eye. It would be possible to modify the template to only show the bar if the user `is_authorized`, effectively limiting the data in the header to logged-in users. This feature would default to showing the bar, but could be enabled via an environment variable. 

What do you think?

**Comment by dizballanze** [comment]
Hi! Sounds good to me. Feel free to open PR!

**Comment by dizballanze** [comment]
[Fixed here](https://pypi.org/project/django-admin-env-notice/1.0/)
