### ISSUE TITLE
In floating mode, banner eventually scrolls off screen

### ISSUE THREAD

**Issue by dmwyatt** [dizballanze/django-admin-env-notice#22]
* django-admin-env-notice version: 0.4
* Django version: 4.0.6
* Python version: 3.8.10
* Operating System: windows/amazon linux

### Description
Float mode works great except if you have longer pages...then it eventually scrolls off-screen as you scroll down the page.

**Comment by olivierdalang** [comment]
Same here. Adding `height: auto` to `<body>` seems to fix it (but didn't test much, not sure if there may be side effects). Would be nice if it worked out of the box !

@dizballanze Would a PR for that be welcome ?

Thanks for the package !

edit: forgot to credit the solution: https://stackoverflow.com/questions/46655386/when-css-position-sticky-stops-sticking

**Comment by dizballanze** [comment]
sure, feel free to open a PR
