### ISSUE TITLE
Incorrect syntax (closing condition)

### ISSUE THREAD

**Issue by eriktelepovsky** [dizballanze/django-admin-env-notice#5]
https://github.com/dizballanze/django-admin-env-notice/blob/0e46f41f93c07f23cad7a4a6a022e0f77f506278/django_admin_env_notice/templates/admin/base_site.html#L16

Incorrect wrapping/closing. Lines 16 and 17 should be switched.

**Comment by dizballanze** [comment]
Thanks, fixed
