### ISSUE TITLE
[feature] text color

### ISSUE THREAD

**Issue by toyg** [dizballanze/django-admin-env-notice#7]
It would be cool to have a third variable for text color, so that using bright banners doesn't result in unreadable white-on-white.

**Comment by dizballanze** [comment]
Hi. That sounds like a good idea, thanks!

**Comment by chesampat** [comment]
Hey @toyg what if there was just a simple variable for light and dark.

Something like `ENVIRONMENT_HEADER_COLOR = "light" | "dark"` and it would default to `"light"` if no option was set.

**Comment by toyg** [comment]
it would be a bit inconsistent to let you configure one color with precision and not the other. 

Full control would also scale better when you have multiple different environments and you can implement unique schemes for each.
